defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "images/backgrounds"
    values:
      background: true

collections:
  pages:
    permalink: /:path/
    output: true

exclude:
  - README.md
  - .gitignore
